project_id = "sajlfpygebpqwzpotrsg"

[functions.send-telegram-notification]
verify_jwt = false

[functions.send-user-telegram-notification]
verify_jwt = false

[functions.cleanup-old-notifications]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false
