import { Link } from 'react-router-dom';
import { useLanguage } from '@/lib/i18n';
import SEO from '@/components/SEO';
import Footer from '@/components/Footer';
import { breadcrumbLd } from '@/lib/seo/structured';
import {
  FileText, UserCog, ShoppingCart, Tag, Truck, RotateCcw, ShieldCheck,
  Store, Gamepad2, Wallet, Copyright, AlertTriangle, Scale, RefreshCw, Mail,
  Crown, Trophy, Printer, Wrench, Bell, Cookie, Lock, MessageSquare,
  Users, Gift, Ticket, Image as ImageIcon, Globe, BadgeCheck, Ban,
  CreditCard, Eye, Megaphone, ScrollText, Building2, FileWarning,
} from 'lucide-react';

const Terms = () => {
  const { language } = useLanguage();

  const c = {
    ar: {
      title: 'الشروط والأحكام',
      desc: 'الإطار القانوني الكامل لاستخدام موقع وتطبيق LEVONIS وشراء المنتجات والمشاركة في الألعاب، المسابقات، الطباعة ثلاثية الأبعاد، خدمات الصيانة، عضويات الولاء، وبرامج الإحالة.',
      updated: 'آخر تحديث: 2026-05-19',
      intro: 'مرحباً بك في LEVONIS. باستخدامك لموقعنا (levonisiq.com / levonis.lovable.app) أو تطبيق LEVONIS الرسمي أو أي خدمة تابعة لنا (يُشار إليها مجتمعةً بـ"المنصة")، فإنك تُقرّ بأنك بالغ سن الرشد القانوني (أو لديك إذن وليّ أمر) وأنك قرأت ووافقت على هذه الشروط والأحكام بكامل بنودها. إذا لم توافق على أي بند، يُرجى التوقف فوراً عن استخدام المنصة. تطبَّق هذه الشروط على جميع الزوّار، المستخدمين المسجّلين، المشترين، التجار، فنيي الصيانة، المشاركين في المسابقات، وأصحاب البطاقات.',
      sections: [
        { icon: FileText, h: '1. التعريفات والمصطلحات', p: '"المنصة" تعني موقع levonisiq.com والمواقع الفرعية وتطبيق LEVONIS الرسمي وأي واجهة برمجية (API) تابعة. "نحن/الشركة" تعني LEVONIS وفريقها وموظفيها وشركاءها التشغيليين. "المستخدم" يشمل أي زائر أو حساب مسجّل أو مشتري أو تاجر أو فني صيانة. "المنتج" يشمل السلع المادية، الخدمات، المنتجات الرقمية، الطلبات المسبقة (Pre-orders)، الطلبات المخصّصة (Custom Requests)، الطباعة ثلاثية الأبعاد، خدمات الصيانة، عضويات الولاء، التذاكر، النقاط، والقسائم. "المحتوى" يشمل النصوص والصور والفيديوهات (الريلز) والتعليقات والتقييمات والشعارات والشيفرة المصدرية.' },
        { icon: UserCog, h: '2. الحساب، التسجيل، والتحقق (KYC)', p: 'يُشترط أن تكون 13 سنة فأكبر للتسجيل (وموافقة وليّ الأمر إن كنت قاصراً). يجب تقديم بيانات حقيقية ومحدّثة (الاسم، الهاتف، البريد، العنوان). نستخدم تأكيد البريد الإلكتروني وقد نطلب توثيقاً إضافياً (KYC) للتجار وللمشاركين في المسابقات الكبرى. أنت مسؤول عن سرية كلمة المرور ورمز PIN الخاص بالمحفظة وعن أي نشاط من حسابك. يُمنع منعاً باتاً إنشاء حسابات متعددة، انتحال هوية، أو مشاركة الحساب مع آخرين. نحتفظ بحق تعليق أو إغلاق أي حساب يخالف الشروط.' },
        { icon: ShoppingCart, h: '3. الطلبات وأنواعها وقبولها', p: 'تدعم المنصة عدة أنواع من الطلبات: (أ) البيع المباشر (من المخزون فوراً)، (ب) الطلبات المسبقة (Pre-orders) بمدة شحن مُعلنة، (ج) الطلبات المخصّصة (Custom Requests)، (د) طلبات طباعة 3D، (ه) طلبات الصيانة، (و) السلال المشتركة (Cart Codes) من التجار. إضافة منتج للسلة لا تُعدّ عقداً ملزماً. يُعتبر الطلب مقبولاً فقط بعد تأكيد فريقنا (هاتفياً، أو إشعار، أو محادثة). نحتفظ بحق رفض أو إلغاء الطلب لأسباب: نفاد مخزون، خطأ تسعير، اشتباه احتيال، عناوين غير قابلة للتوصيل، أو مخالفة للقوانين.' },
        { icon: Tag, h: '4. الأسعار، العروض، والكوبونات', p: 'جميع الأسعار بالدينار العراقي (IQD) ما لم يُذكر خلاف ذلك. تشمل الأسعار الضرائب المعمول بها عند وجودها. تكلفة التوصيل تُحتسب منفصلة وتظهر بوضوح قبل الدفع. تخضع الأسعار للتغيير دون إشعار، لكن السعر المؤكَّد في الطلب لا يتغير بعد التأكيد. الكوبونات والقسائم: لكل كوبون شروط (حد أدنى، فئة محدّدة، صلاحية، عدد استخدامات). يُمنع توليد كوبونات بطرق احتيالية أو تجميع كوبونات لا تنتمي لك. حق الإلغاء: نحتفظ بحق إبطال أي كوبون مُسرَّب أو مُستخدم بسوء نية.' },
        { icon: Wallet, h: '5. المحفظة الإلكترونية والدفع', p: 'الطرق المتاحة: (أ) الدفع عند الاستلام (COD)، (ب) رصيد المحفظة، (ج) الدفع الجزئي بالمحفظة + COD، (د) القسائم وأكواد الخصم، (ه) أي بوابات دفع تُضاف لاحقاً. المحفظة محمية برمز PIN مُشفَّر (لا يمكننا رؤيته)، وأنت المسؤول الوحيد عن حمايته. لا نخزّن أرقام بطاقاتك — تُعالَج عبر بوابات معتمدة (PCI-DSS). شحن المحفظة يتم فقط عبر القنوات الرسمية المُعلنة. السحب النقدي من المحفظة غير متاح إلا في حالات استثنائية يقررها فريق الدعم وفق الشروط.' },
        { icon: CreditCard, h: '6. النقاط، التذاكر، وعملات الموقع الافتراضية', p: 'النقاط (XP/Points) تُكتسب من الشراء (1 دينار = 1 XP)، إكمال الطلبات، الألعاب، والتقييمات. التذاكر تُكتسب أو تُشترى للمشاركة في المسابقات وألعاب اليانصيب. النقاط، التذاكر، الكوبونات، XP المستوى، وأي عملة افتراضية في المنصة ليست عملة قانونية، ولا تُستبدل بنقد، ولا تُحوَّل لحسابات أخرى إلا عبر ميزات الإهداء الرسمية، وقد تنتهي صلاحيتها أو تُعدَّل وفق شروط برامج المكافآت.' },
        { icon: Truck, h: '7. التوصيل، الاستلام، الفحص، والشحن الدولي', p: 'مدة التوصيل تقديرية: 1-3 أيام لبغداد، 3-7 أيام لباقي المحافظات، والطلبات المسبقة وفق المدة المُعلنة في صفحة المنتج. خيارات: (1) الاستلام من المخزن مجاناً، (2) التوصيل الاعتيادي، (3) التوصيل الشخصي السريع. تخضع جميع الطلبات قبل الشحن لفحص داخلي يشمل: العدد، الألوان، الخيارات والمواصفات المختارة في صفحة المنتج، الاكسسوارات، اختبار التشغيل الأولي للأجهزة، وسلامة التغليف — ويُعتمد سجل الفحص كمرجع رسمي في أي نزاع. يلتزم العميل بفحص الطلب أمام مندوب التوصيل قبل التوقيع، وأي اختلاف في الكمية، اللون، الخيار، أو المواصفات يجب توثيقه (صورة/فيديو وملاحظة لدى المندوب أو رفض الاستلام) في تلك اللحظة فقط؛ فإذا كان المُسلَّم مطابقاً لما هو مثبت في صفحة الطلب داخل الموقع ولم يُسجَّل أي اعتراض أمام المندوب، يسقط حق العميل في الاعتراض اللاحق على المحتوى الظاهر. التأخيرات الناتجة عن قوة قاهرة (طقس، إغلاق طرق، أحداث أمنية، إضراب، تعطل أنظمة شركات الشحن) لا تُعدّ إخلالاً. العميل مسؤول عن صحة العنوان ورقم الهاتف والتواجد لاستلام الطلب — في حال فشل التوصيل لأسباب تخص العميل قد تُحتسب رسوم إعادة توصيل.' },
        { icon: RotateCcw, h: '8. الإرجاع، الاستبدال، والاسترداد', p: 'يحق لك إرجاع/استبدال المنتج خلال 7 أيام تبدأ من تاريخ تسليم الطلب فعلياً، وذلك حصراً إذا: (1) كان معيباً مصنعياً ظاهراً، (2) مختلفاً عن الموصوف داخل صفحة المنتج/الطلب في الموقع (الكمية، اللون، الخيار، أو المواصفات)، (3) غير مستخدم وفي تغليفه الأصلي بكامل اكسسواراته. الاختلاف في الذوق الشخصي أو تغيير الرأي ليس سبباً للاسترجاع. لا تشمل سياسة الإرجاع: المنتجات المخصّصة، طلبات الطباعة 3D، البرامج المُفعّلة، الاكسسوارات المفتوحة، المنتجات الاستهلاكية، الجوائز، والعروض الترويجية المحدودة. أي طلب أو اتفاق أو تعديل يتم خارج الموقع (تواصل خاص، رسائل خارجية، اتفاق شفهي، أو أي تعديل لم يُوثَّق في صفحة الطلب داخل الموقع) لا تتحمل المنصة أي مسؤولية تجاهه ولا يحق للعميل المطالبة بأي استرجاع أو تعويض أو ضمان عنه. الاسترداد يكون لمحفظة المنصة افتراضياً، أو لطريقة الدفع الأصلية وفق سياسة كل بوابة. تكلفة شحن الإرجاع: علينا إذا كان الخطأ منا، عليك إذا كان لتغيير الرأي.' },
        { icon: ShieldCheck, h: '9. الضمان، شروط تفعيله، وخطط الحماية', p: 'يخضع كل منتج لضمان رسمي محدد المدة (يظهر في صفحته). يُغطّي الضمان عيوب التصنيع فقط. لا يشمل: سوء الاستخدام، الكسر العرضي، الفتح من جهات غير معتمدة، تلف السوائل، التعرض لتيار غير مناسب، الكوارث الطبيعية، أو المواد الاستهلاكية. يُشترط للاستفادة من الضمان على الطابعات: (1) أن تكون الطابعة مُسجَّلة داخل نظام المنصة ومرتبطة بحساب العميل نفسه عبر ميزة "تفعيل الضمان" والرقم التسلسلي، (2) أن يقوم العميل بإحضار الطابعة بنفسها إلى المخزن أو المكتب الرسمي للمنصة لإجراء الفحص الفني قبل أي قرار باستبدال أو تعويض، (3) ألا تكون الطابعة قد فُتحت أو عُدِّلت من جهة غير معتمدة، (4) الاحتفاظ بفاتورة الشراء. لا يتم استبدال أي قطعة أو صرف أي تعويض نقدي قبل إتمام الفحص الفني داخل المنصة، وأي طابعة غير مسجَّلة في حساب العميل أو لم تُفحَص من قبل المنصة تسقط عنها كافة حقوق الضمان والتعويض. التعويض النقدي بديلاً عن الإصلاح أو الاستبدال يكون وفق تقدير المنصة فقط. خطط حماية الطابعات (Printer Protection): اشتراكات اختيارية مدفوعة بشروط منفصلة موضحة عند الشراء.' },
        { icon: Wrench, h: '10. خدمات الصيانة وفنيي الصيانة', p: 'تُقدَّم الصيانة عبر فنيين معتمدين أو شركاء. تحديد الكلفة بعد الفحص. أي قطع غيار تُستبدل تخضع لضمان منفصل. المحادثة مع "دعم الصيانة" قد تُسجَّل لأغراض الجودة. أنت مسؤول عن النسخ الاحتياطي لبياناتك قبل تسليم الجهاز — لا نتحمل مسؤولية فقدان البيانات. رفض إصلاح الجهاز بعد الفحص قد يستلزم رسم فحص رمزي يُعلَن مسبقاً.' },
        { icon: Printer, h: '11. خدمات الطباعة ثلاثية الأبعاد (Community Print)', p: 'منصة طلبات الطباعة 3D تربط العملاء بالتجار/الفنيين. يقدّم العملاء وصفاً، صوراً، أو ملفات مرجعية، ويتلقّون عروضاً سعرية من التجار. يُحفَظ المبلغ في حساب وسيط (Escrow) ولا يُفرَج عنه للتاجر إلا بعد تأكيد العميل للاستلام أو بعد المدة التلقائية. العميل مسؤول قانونياً عن أن التصاميم لا تنتهك حقوق ملكية فكرية لأي طرف ثالث. التاجر مسؤول عن جودة المنتج والمواد المستخدمة.' },
        { icon: Store, h: '12. مجتمع التجار (Marketplace) والشراكات', p: 'التسجيل كتاجر يخضع لاتفاقية شراكة منفصلة. التجار مسؤولون قانونياً عن منتجاتهم، أوصافها، أسعارها، ضماناتها، والامتثال للقوانين العراقية. تأخذ LEVONIS عمولة على كل عملية بنسبة معلنة. يلتزم التجار بمعايير الجودة، الردّ السريع، عدم بيع منتجات مقلَّدة أو محظورة. نحتفظ بحق تعليق التاجر أو حجب أرباحه عند المخالفة. عضوية VIP Plus للتجار توفر مزايا استثمارية بشروط منفصلة.' },
        { icon: Crown, h: '13. عضويات الولاء (Loyalty Cards) و VIP Plus', p: 'تتوفر بطاقات ولاء بمستويات (مثل Bronze, Silver, Gold, VIP, VIP Plus) قابلة للشراء أو الإهداء بالنقاط/المحفظة. كل بطاقة توفر مزايا (خصومات على فئات، توصيل مخفّض، عروض حصرية) محددة في صفحة البطاقة وقت الاشتراك. الاشتراكات الشهرية تتجدد آلياً ما لم تُلغها قبل تاريخ التجديد. لا تُسترد رسوم البطاقات بعد الاستخدام. نحتفظ بحق تعديل المزايا مع إشعار مسبق 14 يوماً.' },
        { icon: Trophy, h: '14. المسابقات، اليانصيب، والألعاب', p: 'تشمل: مسابقات اليانصيب التقليدي، السحوبات بأرقام التذاكر، مسابقات جمع الحروف، مسابقات الفِرَق، صناديق الغموض (Mystery Box)، الجوائز المتنامية، الفلاش، الألعاب التفاعلية (Crossy Road, Stack, Space Blaster, Tower, ...). جميعها لأغراض ترفيهية وتسويقية ويُعلَن لكلٍّ منها آلية الفوز ونسب الاحتمالات. يُمنع: استخدام بوتات، حسابات متعددة، استغلال ثغرات، أو التواطؤ. أي مخالفة تُلغي الجائزة وتغلق الحساب وتُحجب الأرباح. النقاط والتذاكر ليست عملة وقد لا تنطبق عليها قوانين القمار في بعض البلدان — يقع على المستخدم التحقق من قانونية المشاركة في بلده.' },
        { icon: Gift, h: '15. الجوائز، الإهداء، والمكافآت', p: 'الجوائز العينية تُسلَّم بعد تحقق الفوز وتأكيد عنوان المستلم. الجوائز الرقمية (كوبونات، تذاكر، نقاط) تُمنح تلقائياً للحساب. مدة استلام الجوائز العينية تصل لـ 30 يوماً (قد تختلف حسب نوع الجائزة). يحق إهداء البطاقات/المنتجات وفق ميزات الإهداء الرسمية فقط. المكافآت من برامج الإحالة (Referral) تُمنح بعد إكمال الإحالة عملية الشراء الأولى المؤهلة.' },
        { icon: Ticket, h: '16. برنامج الإحالات (Referrals)', p: 'كل مستخدم يحصل على رمز إحالة فريد. عند استخدامه من مستخدم جديد يحصل الطرفان على مكافأة معلنة. يُمنع: الإحالة الذاتية، استخدام حسابات وهمية، نشر الكود في مواقع سبام. المكافآت تُلغى عند اكتشاف التلاعب. أصحاب VIP Plus يمكنهم تخصيص لافتة الإحالة الظاهرة للمشترين بكودهم وفق الشروط.' },
        { icon: Users, h: '17. المحتوى الذي ينشئه المستخدمون (UGC) والمجتمع', p: 'بنشرك تعليقات، تقييمات، صور، فيديو، أو منشورات في أقسام المجتمع تمنح LEVONIS ترخيصاً عالمياً، غير حصري، خالياً من الإتاوات لاستخدام، تعديل، عرض، وتوزيع هذا المحتوى لأغراض تشغيل المنصة وتسويقها. تتعهد بأنك مالك المحتوى أو لديك صلاحية نشره. يُمنع نشر محتوى مسيء، عنصري، إباحي، يحرّض على العنف، أو ينتهك حقوق الغير. نحتفظ بحق إخفاء/حذف أي محتوى دون إشعار.' },
        { icon: MessageSquare, h: '18. المحادثات، الدعم، وتسجيل الجودة', p: 'المحادثات مع الدعم، الصيانة، التجار، أو ضمن الطلبات قد تُحفَظ وتُراجَع لضمان الجودة وحل النزاعات. يُمنع استخدام لغة مسيئة أو تهديدية. لا يُسمح بمشاركة بيانات مالية حساسة عبر الشات. المحادثات الإدارية للطلبات قد تُربَط ببوتات Telegram للإشعارات.' },
        { icon: Bell, h: '19. الإشعارات والتسويق', p: 'بإنشاء حساب توافق على تلقّي إشعارات تشغيلية (تحديثات الطلبات، الفواتير، الضمان، الأمان). الإشعارات التسويقية (عروض، مسابقات) اختيارية ويمكن إيقافها من الإعدادات. قد نرسل إشعارات Push، بريد إلكتروني، رسائل WhatsApp/SMS، أو إشعارات Telegram. لا نشارك بياناتك مع جهات إعلانية خارجية بغرض التسويق المباشر.' },
        { icon: Megaphone, h: '20. الريلز (Reels) والإعلانات والبنرات', p: 'الريلز والبنرات والإعلانات تُعرَض عبر المنصة. قد تكون مُروَّجة من LEVONIS أو من شركاء. لا نضمن دقة المحتوى الإعلاني للأطراف الثالثة. نحتفظ بحق رفض أي إعلان يخالف سياسات المحتوى أو القوانين.' },
        { icon: Cookie, h: '21. ملفات تعريف الارتباط (Cookies) والتخزين المحلي', p: 'نستخدم Cookies و localStorage لأغراض: المصادقة، تذكّر التفضيلات (اللغة، الثيم)، السلة، تحليلات مجهولة الهوية. يمكنك تعطيلها من المتصفح، لكن قد تتأثر بعض الميزات. لا نستخدم Cookies لأغراض تتبّع إعلاني خارجي.' },
        { icon: Eye, h: '22. الخصوصية وحماية البيانات', p: 'تُعالَج بياناتك وفق سياسة الخصوصية (انظر /privacy)، التي تُعدّ جزءاً لا يتجزأ من هذه الشروط. نتخذ تدابير تقنية وتنظيمية معقولة لحماية بياناتك (تشفير TLS، PIN مُشفَّر، RLS على قواعد البيانات)، لكن لا يمكن ضمان الأمان المطلق على الإنترنت.' },
        { icon: Lock, h: '23. الأمان السيبراني وحماية الحساب', p: 'يُمنع: محاولات اختراق، هجمات DOS/DDOS، استغلال ثغرات (يجب الإبلاغ عبر security@levonisiq.com للحصول على مكافأة محتملة)، الهندسة العكسية للتطبيق، تجريف البيانات (Scraping) الآلي. أي نشاط مشبوه يؤدي للحظر الفوري وقد يُحال للجهات المختصة.' },
        { icon: Copyright, h: '24. الملكية الفكرية وحقوق النشر', p: 'جميع المحتويات (الشعار، التصميم، الواجهات، النصوص، الصور، الكود المصدري، قواعد البيانات، الأيقونات، الخطوط) ملك حصري لـ LEVONIS أو مرخّصة لها. يُمنع نسخ، تعديل، عكس هندسي، أو إعادة استخدام أي جزء دون إذن كتابي. صور المنتجات قد تكون من المُصنّعين وتُستخدم بحقوق الاستخدام العادل. لتقديم بلاغ DMCA: legal@levonisiq.com.' },
        { icon: ImageIcon, h: '25. صور المنتجات والمواصفات', p: 'الصور توضيحية وقد تختلف الألوان قليلاً بسبب إعدادات الشاشات. المواصفات التقنية مأخوذة من المُصنّع وقد تُحدَّث. في حال وجود تباين جوهري بين المنتج المستلم والوصف، يُطبَّق بند الإرجاع.' },
        { icon: Ban, h: '26. الاستخدام المحظور', p: 'يُمنع: (أ) أي استخدام غير قانوني أو مخالف للنظام العام، (ب) محاولات الاحتيال أو غسيل الأموال، (ج) إنشاء حسابات وهمية أو متعددة، (د) استغلال أنظمة المكافآت/الكوبونات/الإحالات بسوء نية، (ه) نشر محتوى مسيء/عنصري/إباحي، (و) انتحال هوية موظفي LEVONIS أو الحكومة، (ز) بيع منتجات محظورة (أسلحة، مخدرات، مواد خاضعة للعقوبات)، (ح) استخدام المنصة لإرسال سبام، (ط) تجاوز إجراءات الأمان أو القيود الجغرافية.' },
        { icon: BadgeCheck, h: '27. التقييمات والمراجعات', p: 'التقييمات تنعكس فقط بعد عملية شراء حقيقية موثّقة. التقييم التلقائي 5 نجوم يُطبَّق بعد 7 أيام إذا لم يقيّم المستخدم. يُمنع التقييم الزائف، تبادل التقييمات، أو الابتزاز عبر التقييمات. نحتفظ بحق إخفاء التقييمات المسيئة أو غير ذات الصلة.' },
        { icon: FileWarning, h: '28. حدود المسؤولية والإخلاء', p: 'تُقدَّم خدماتنا "كما هي" و"كما هي متاحة". لا نضمن خلو المنصة من الأعطال، الانقطاعات، أو الأخطاء. مسؤوليتنا القصوى لأي ضرر مباشر تقتصر على القيمة الفعلية للطلب المعني خلال آخر 30 يوماً. لا نتحمل أي مسؤولية عن: أضرار غير مباشرة، فقدان أرباح/فرص/سمعة/بيانات، أعمال أطراف ثالثة (شركات الشحن، بوابات الدفع، التجار، فنيي الصيانة، شبكات الاتصالات).' },
        { icon: ShieldCheck, h: '29. التعويض (Indemnification)', p: 'توافق على تعويض LEVONIS وموظفيها وشركائها وحمايتهم من أي مطالبات، خسائر، أو نفقات (بما فيها أتعاب المحاماة) ناتجة عن: مخالفتك للشروط، انتهاكك لحقوق الغير، استخدامك غير القانوني للمنصة، أو محتوى نشرته.' },
        { icon: Building2, h: '30. القوة القاهرة', p: 'لا تتحمل LEVONIS أي مسؤولية عن التأخير أو الإخلال الناتج عن قوة قاهرة: الكوارث الطبيعية، الحروب، الأوبئة، الإضرابات، انقطاع الإنترنت أو الكهرباء، قرارات حكومية، إغلاق الموانئ والمعابر، أو أي حدث خارج سيطرتنا المعقولة.' },
        { icon: RefreshCw, h: '31. الإنهاء وإغلاق الحساب', p: 'يحق لك إغلاق حسابك في أي وقت من الإعدادات (بشرط عدم وجود طلبات/التزامات معلّقة). يحق لنا تعليق أو إنهاء حسابك فوراً عند مخالفة الشروط، مع الاحتفاظ بحقنا في المطالبة بالتعويض. الرصيد في المحفظة المُجمَّد بسبب احتيال لا يُسترَد. عند الإنهاء تظل بنود الملكية الفكرية، التعويض، حدود المسؤولية، والقانون الحاكم نافذة.' },
        { icon: Globe, h: '32. القاصرون والاستخدام العائلي', p: 'الخدمات مخصّصة لمن هم 13 سنة فأكبر. القاصرون (13-18) يجب أن يستخدموا المنصة تحت إشراف وليّ الأمر الذي يقبل المسؤولية الكاملة عن مشترياتهم وأنشطتهم. يُمنع منعاً باتاً مشاركة الأطفال دون 13 سنة في المسابقات أو إنشاء حسابات.' },
        { icon: Scale, h: '33. القانون الحاكم وتسوية النزاعات', p: 'تخضع هذه الشروط وتُفسَّر وفقاً للقوانين النافذة في جمهورية العراق. نسعى لحلّ النزاعات ودياً عبر فريق الدعم خلال 30 يوماً. في حال تعذُّر ذلك، تختص محاكم بغداد المختصّة بالنظر في أي نزاع. يحق لنا فرض التحكيم بدلاً من التقاضي وفق القواعد المعمول بها في العراق.' },
        { icon: ScrollText, h: '34. القابلية للفصل والتنازل', p: 'إذا اعتُبر أيّ بند غير قابل للتنفيذ، يبقى باقي الشروط نافذاً. عدم ممارستنا لحقّ ما لا يُعدّ تنازلاً عنه. لا يحق لك التنازل عن حقوقك في هذه الاتفاقية لطرف ثالث دون موافقتنا الكتابية، بينما يحق لنا التنازل عن حقوقنا والتزاماتنا لأي شركة تابعة أو خَلَف قانوني.' },
        { icon: RefreshCw, h: '35. تعديل الشروط', p: 'نحتفظ بحق تعديل هذه الشروط في أي وقت. التعديلات الجوهرية يُعلَن عنها داخل المنصة و/أو عبر البريد الإلكتروني قبل 14 يوماً من سريانها. استمرارك في استخدام الخدمات بعد سريان التعديلات يُعدّ موافقة ضمنية. إذا لم توافق، يجب التوقف عن استخدام المنصة.' },
        { icon: Mail, h: '36. التواصل والشكاوى الرسمية', p: 'لأي استفسار قانوني، شكوى رسمية، أو طلب ممارسة حقوقك بموجب الخصوصية: WhatsApp: +964 783 845 5220 — البريد القانوني: legal@levonisiq.com — البريد الأمني: security@levonisiq.com — الدعم العام: support@levonisiq.com.' },
      ],
    },
    en: {
      title: 'Terms of Use',
      desc: 'Comprehensive legal framework for using LEVONIS, purchasing products, and participating in games, competitions, 3D printing, maintenance, loyalty memberships, and referral programs.',
      updated: 'Last updated: 2026-05-19',
      intro: 'Welcome to LEVONIS. By using our website (levonisiq.com / levonis.lovable.app), the official LEVONIS app, or any related service (collectively, the "Platform"), you confirm that you are of legal age (or have parental consent) and that you have read and agreed to these Terms in full. If you do not agree to any clause, please stop using the Platform immediately. These Terms apply to all visitors, registered users, buyers, merchants, maintenance technicians, competition participants, and cardholders.',
      sections: [
        { icon: FileText, h: '1. Definitions', p: '"Platform" means levonisiq.com, related sub-domains, the official LEVONIS app, and any related API. "We/Company" means LEVONIS, its team, employees, and operating partners. "User" includes any visitor, registered account, buyer, merchant, or technician. "Product" includes physical goods, services, digital products, pre-orders, custom requests, 3D printing, maintenance, loyalty memberships, tickets, points, and coupons. "Content" includes text, images, video reels, comments, ratings, logos, and source code.' },
        { icon: UserCog, h: '2. Account, Registration & KYC', p: 'You must be 13+ to register (with parental consent if minor). You must provide accurate, up-to-date information (name, phone, email, address). We use email confirmation and may require additional verification (KYC) for merchants and major-competition participants. You are responsible for the confidentiality of your password and wallet PIN and for any activity from your account. Multiple accounts, identity impersonation, or account sharing are strictly prohibited. We may suspend or close any non-compliant account.' },
        { icon: ShoppingCart, h: '3. Order Types & Acceptance', p: 'The Platform supports several order types: (a) Direct Sale (immediate stock), (b) Pre-orders with announced shipping windows, (c) Custom Requests, (d) 3D printing requests, (e) Maintenance, (f) merchant Cart Codes. Adding to cart is not a binding contract. An order is considered accepted only after our team confirms it (by phone, notification, or chat). We may decline or cancel for: stock-out, pricing errors, fraud suspicion, undeliverable addresses, or legal violations.' },
        { icon: Tag, h: '4. Pricing, Offers & Coupons', p: 'All prices are in Iraqi Dinar (IQD) unless stated otherwise. Prices include applicable taxes when present. Delivery is calculated separately and shown clearly before payment. Prices may change without notice; a confirmed order keeps its price. Coupons have specific conditions (minimum purchase, category, expiry, usage cap). Generating coupons fraudulently or stacking ineligible coupons is prohibited. We reserve the right to invalidate any leaked or abused coupon.' },
        { icon: Wallet, h: '5. e-Wallet & Payments', p: 'Available methods: (a) Cash on Delivery, (b) wallet balance, (c) partial wallet + COD, (d) coupons, (e) any future payment gateways. The wallet is protected by an encrypted PIN we cannot view; you are solely responsible for protecting it. We never store card numbers; they are processed via certified gateways (PCI-DSS). Wallet top-ups are only via official channels. Cash withdrawal is not available except in exceptional cases approved by support.' },
        { icon: CreditCard, h: '6. Points, Tickets & Virtual Currency', p: 'Points (XP) are earned via purchases (1 IQD = 1 XP), order completion, games, and reviews. Tickets are earned or purchased to enter competitions and lottery games. Points, tickets, coupons, level XP, and any in-platform virtual currency are NOT legal tender, are not redeemable for cash, and are not transferable except via official gifting features. They may expire or be adjusted per program rules.' },
        { icon: Truck, h: '7. Delivery, Pickup, Inspection & Force Majeure', p: 'Delivery times are estimates: 1-3 days for Baghdad, 3-7 days for other governorates, pre-orders per the announced window. Options: warehouse pickup (free), standard delivery, personal express delivery. All orders undergo an internal pre-shipping inspection covering quantity, colors, the selected options/specs from the product page, accessories, an initial power-on test for devices, and packaging integrity; the inspection record is the official reference in any dispute. The customer must inspect the order in front of the delivery agent before signing, and any difference in quantity, color, option, or specs must be documented (photo/video + note with the agent or refusing receipt) at that moment only. If the delivered item matches what is recorded on the order page on the site and no objection was raised in front of the agent, the customer forfeits the right to object later to the visible contents. Force-majeure delays (weather, road closures, security events, strikes, carrier outages) are not breaches. The user is responsible for accurate address/phone and being available; failed deliveries due to user fault may incur re-delivery fees.' },
        { icon: RotateCcw, h: '8. Returns, Exchanges & Refunds', p: 'You may return/exchange within 7 days from actual delivery date, exclusively if: (1) the product is visibly defective from manufacturing, (2) different from what is described on the product/order page on the site (quantity, color, option, specs), (3) unused in original packaging with all accessories. Change of mind/personal taste is not a valid reason. Excluded: custom products, 3D printing, activated software, opened consumables, prizes, and limited promotional offers. Any order, agreement, or modification done outside the site (private contact, external messages, verbal arrangements, or anything not recorded on the order page) is not the platform’s responsibility, and the customer has no right to any refund, compensation, or warranty for it. Refunds default to the platform wallet, or to the original payment method per gateway policy. Return shipping is on us if our fault, on you if change of mind.' },
        { icon: ShieldCheck, h: '9. Warranty, Activation Requirements & Protection Plans', p: 'Each product has an official warranty period (shown on its page). Covers manufacturing defects only. Excludes misuse, accidental damage, unauthorized opening, liquid damage, improper voltage, natural disasters, and consumables. For printer warranty: (1) the printer must be registered in the platform system and linked to the same customer’s account via the "Warranty Activation" feature and serial number, (2) the customer must bring the printer itself to the platform’s official warehouse or office for technical inspection before any replacement or compensation decision, (3) the printer must not have been opened or modified by any unauthorized party, (4) the purchase invoice must be kept. No part is replaced and no monetary compensation is paid before the technical inspection at the platform is completed; any printer not registered in the customer’s account or not inspected by the platform forfeits all warranty and compensation rights. Monetary compensation in lieu of repair/replacement is at the platform’s sole discretion. Printer Protection Plans are optional paid subscriptions with separate terms.' },
        { icon: Wrench, h: '10. Maintenance Services', p: 'Maintenance is provided by certified technicians or partners. Cost is determined after diagnosis. Any replaced parts have separate warranties. Conversations with "Maintenance Support" may be recorded for quality. You are responsible for backing up your data before delivering devices — we are not liable for data loss. Refusing repair after diagnosis may incur a nominal diagnostic fee announced in advance.' },
        { icon: Printer, h: '11. 3D Printing (Community Print)', p: 'The 3D-print marketplace connects customers with merchants/technicians. Customers submit descriptions, photos, or reference files and receive bids. Funds are held in escrow and released to the merchant only after customer confirmation or auto-confirmation period. The customer is legally responsible that designs do not infringe third-party IP. The merchant is responsible for product quality and materials.' },
        { icon: Store, h: '12. Merchant Marketplace & Partnerships', p: 'Merchant registration is governed by a separate partnership agreement. Merchants are legally responsible for products, descriptions, prices, warranties, and Iraqi-law compliance. LEVONIS takes a published commission per transaction. Merchants must meet quality standards, respond promptly, and not sell counterfeit/prohibited goods. We may suspend merchants and withhold earnings for violations. Merchant VIP Plus offers investment perks under separate terms.' },
        { icon: Crown, h: '13. Loyalty Cards & VIP Plus', p: 'Loyalty cards exist in tiers (e.g., Bronze, Silver, Gold, VIP, VIP Plus) and may be purchased or gifted via points/wallet. Each tier offers benefits (category discounts, reduced delivery, exclusive offers) listed on its page at the time of subscription. Monthly subscriptions auto-renew unless cancelled before renewal. Card fees are non-refundable after use. We may modify benefits with 14 days notice.' },
        { icon: Trophy, h: '14. Competitions, Lottery & Games', p: 'Includes: classical lottery, ticket draws, letter-collection competitions, team competitions, mystery boxes, growing prizes, flash competitions, interactive games (Crossy Road, Stack, Space Blaster, Tower, etc.). All are entertainment/marketing rewards with announced odds and mechanics. Bots, multi-accounts, exploit abuse, or collusion are prohibited and result in prize cancellation, account closure, and forfeited earnings. Points/tickets are not legal currency; users must verify legality of participation in their jurisdiction.' },
        { icon: Gift, h: '15. Prizes, Gifting & Rewards', p: 'Physical prizes are delivered after winner verification and address confirmation. Digital prizes (coupons, tickets, points) are credited automatically. Physical prize claim window is up to 30 days (varies by prize). Cards/products may be gifted only via official gifting features. Referral rewards are credited after the referred user completes their first qualifying purchase.' },
        { icon: Ticket, h: '16. Referral Program', p: 'Each user gets a unique referral code. When used by a new user, both parties receive an announced reward. Self-referral, fake accounts, and spam posting are prohibited. Rewards are revoked upon detection of abuse. VIP Plus owners may customize the referral banner shown to buyers using their code, per the relevant terms.' },
        { icon: Users, h: '17. User-Generated Content (UGC) & Community', p: 'By posting comments, reviews, photos, video, or community posts you grant LEVONIS a worldwide, non-exclusive, royalty-free license to use, modify, display, and distribute the content for operating and marketing the Platform. You warrant you own the content or have permission to post it. Posting offensive, discriminatory, pornographic, violence-inciting, or rights-infringing content is prohibited. We may hide/remove content without notice.' },
        { icon: MessageSquare, h: '18. Chats, Support & Quality Recording', p: 'Chats with support, maintenance, merchants, or in-order chats may be stored and reviewed for quality and dispute resolution. Abusive or threatening language is prohibited. Sharing sensitive financial data via chat is not allowed. Admin order chats may be linked to Telegram bots for notifications.' },
        { icon: Bell, h: '19. Notifications & Marketing', p: 'By creating an account you consent to operational notifications (order updates, invoices, warranty, security). Marketing notifications (offers, competitions) are optional and can be disabled in settings. We may send Push, email, WhatsApp/SMS, or Telegram notifications. We do not share your data with external advertisers for direct marketing.' },
        { icon: Megaphone, h: '20. Reels, Ads & Banners', p: 'Reels, banners, and ads displayed on the Platform may be from LEVONIS or partners. We do not warrant the accuracy of third-party advertising. We may reject any ad violating content policies or law.' },
        { icon: Cookie, h: '21. Cookies & Local Storage', p: 'We use cookies and localStorage for: authentication, preference memory (language, theme), cart, and anonymous analytics. You may disable them in your browser, but some features may be affected. We do not use cookies for external ad tracking.' },
        { icon: Eye, h: '22. Privacy & Data Protection', p: 'Your data is processed per our Privacy Policy (see /privacy), which is an integral part of these Terms. We apply reasonable technical and organizational measures (TLS encryption, hashed PINs, RLS on databases), but absolute internet security cannot be guaranteed.' },
        { icon: Lock, h: '23. Cybersecurity & Account Protection', p: 'Hacking attempts, DOS/DDOS, vulnerability exploitation (please report via security@levonisiq.com for a possible bounty), reverse engineering, and automated scraping are prohibited. Suspicious activity results in immediate ban and possible referral to authorities.' },
        { icon: Copyright, h: '24. Intellectual Property & DMCA', p: 'All content (logo, design, UI, text, images, source code, databases, icons, fonts) is the exclusive property of LEVONIS or licensed to it. Copying, modifying, reverse engineering, or reusing any part without written permission is prohibited. Product images may be from manufacturers under fair use. DMCA notices: legal@levonisiq.com.' },
        { icon: ImageIcon, h: '25. Product Images & Specifications', p: 'Images are illustrative; colors may vary slightly with display settings. Technical specs are sourced from manufacturers and may be updated. If a received product materially differs from the description, the return policy applies.' },
        { icon: Ban, h: '26. Prohibited Use', p: 'Forbidden: (a) any illegal use, (b) fraud or money laundering attempts, (c) fake or multiple accounts, (d) abuse of rewards/coupons/referrals, (e) offensive/racist/pornographic content, (f) impersonating staff or government, (g) selling prohibited goods (weapons, drugs, sanctioned items), (h) spamming, (i) bypassing security or geographic restrictions.' },
        { icon: BadgeCheck, h: '27. Reviews & Ratings', p: 'Ratings reflect verified purchases only. A 5-star automatic rating applies after 7 days if the user does not rate. Fake reviews, review trading, or extortion via reviews are prohibited. We may hide offensive or irrelevant reviews.' },
        { icon: FileWarning, h: '28. Limitation of Liability & Disclaimer', p: 'Our services are provided "AS IS" and "AS AVAILABLE". We do not warrant the Platform is free from outages or errors. Our maximum liability for any direct damage is limited to the actual value of the relevant order within the past 30 days. We are not liable for indirect damages, lost profits/opportunities/reputation/data, or third-party actions (carriers, gateways, merchants, technicians, telecoms).' },
        { icon: ShieldCheck, h: '29. Indemnification', p: 'You agree to indemnify and hold LEVONIS, its employees, and partners harmless from any claims, losses, or expenses (including legal fees) arising from: your breach of these Terms, your violation of third-party rights, your unlawful use of the Platform, or content you posted.' },
        { icon: Building2, h: '30. Force Majeure', p: 'LEVONIS is not liable for delays or breaches caused by force majeure: natural disasters, war, pandemics, strikes, internet/electricity outages, government decisions, port/border closures, or any event beyond reasonable control.' },
        { icon: RefreshCw, h: '31. Termination & Account Closure', p: 'You may close your account anytime from settings (provided no pending orders/obligations). We may suspend or terminate immediately upon breach, while reserving the right to claim damages. Wallet balances frozen due to fraud are non-refundable. After termination, IP, indemnification, liability limits, and governing law clauses survive.' },
        { icon: Globe, h: '32. Minors & Family Use', p: 'Services are intended for users 13+. Minors (13-18) must use the Platform under parental supervision; the parent accepts full responsibility for purchases and activities. Children under 13 may not participate in competitions or create accounts.' },
        { icon: Scale, h: '33. Governing Law & Disputes', p: 'These Terms are governed by the laws of the Republic of Iraq. We aim to resolve disputes amicably via support within 30 days. Otherwise, the competent Baghdad courts have jurisdiction. We may opt for arbitration instead of litigation per applicable Iraqi rules.' },
        { icon: ScrollText, h: '34. Severability & Assignment', p: 'If any clause is unenforceable, the remainder remains in effect. Failure to exercise a right is not a waiver. You may not assign your rights to a third party without our written consent; we may assign our rights and obligations to any affiliate or legal successor.' },
        { icon: RefreshCw, h: '35. Modification', p: 'We may modify these Terms anytime. Material changes are announced on the Platform and/or via email at least 14 days before effect. Continued use after the effective date is implied acceptance. If you disagree, you must stop using the Platform.' },
        { icon: Mail, h: '36. Contact & Formal Complaints', p: 'For legal questions, formal complaints, or to exercise privacy rights: WhatsApp: +964 783 845 5220 — Legal: legal@levonisiq.com — Security: security@levonisiq.com — General Support: support@levonisiq.com.' },
      ],
    },
    ku: {
      title: 'مەرجەکانی بەکارهێنان',
      desc: 'چوارچێوەی یاسایی تەواوی بەکارهێنانی LEVONIS و بەشداریکردن لە یاری، پێشبڕکێ، چاپی سێ ڕەهەندی، چاککردنەوە، و بەرنامەی وەفاداری.',
      updated: 'دوایین نوێکردنەوە: 2026-05-19',
      intro: 'بەخێربێیت بۆ LEVONIS. بە بەکارهێنانی ماڵپەڕ و ئەپڵیکەیشن و خزمەتگوزاریەکانمان، تۆ ڕازیت بەم مەرجانەی خوارەوە. ئەگەر ڕازی نیت، تکایە بەکارهێنانی پلاتفۆڕم بوەستێنە.',
      sections: [
        { icon: FileText, h: '١. پێناسەکان', p: 'پلاتفۆڕم: levonisiq.com و ئەپی LEVONIS و هەر API پەیوەندیدار. بەکارهێنەر: هەر سەردانیکار، حساب، کڕیار، یان بازرگان.' },
        { icon: UserCog, h: '٢. هەژمار و KYC', p: 'دەبێت ١٣ ساڵ بەرەو سەرە بیت. زانیاری ڕاست بدە. بەرپرسی نهێنیی ووشەی نهێنی و PIN-ی جزدانت هەیە. حسابی فرە و ناوی ساختە قەدەغەیە.' },
        { icon: ShoppingCart, h: '٣. داواکاریەکان', p: 'جۆرەکان: فرۆشتنی ڕاستەوخۆ، پێش-داواکاری، داواکاری تایبەت، چاپی 3D، چاککردنەوە. داواکاری تەنها دوای دڵنیاکردنەوەی تیمی ئێمە وەردەگیرێت.' },
        { icon: Tag, h: '٤. نرخ، پێشکەشکراو و کوپۆن', p: 'نرخ بە دینار. تێچووی گەیاندن جیاوازە. کوپۆن مەرجی تایبەتی هەیە (کاتی بەسەرچوون، کەمترین مبلغ).' },
        { icon: Wallet, h: '٥. جزدان و پارەدان', p: 'پارەدان لە کاتی وەرگرتن، باڵانسی جزدان (بە PIN پارێزراوە)، یان کوپۆن. ژمارەی کارت لە لای ئێمە پاشەکەوت ناکرێت.' },
        { icon: CreditCard, h: '٦. خاڵ، تکت و دراوی نائاسایی', p: 'خاڵ (XP) لە کڕین (١ دینار = ١ XP) و یاری دێت. تکت بۆ بەشداری لە پێشبڕکێ. ئەمانە دراوی یاسایی نین و بە پارە ناگۆڕدرێن.' },
        { icon: Truck, h: '٧. گەیاندن', p: 'گەیاندن لە ١-٣ ڕۆژدا بۆ بەغدا و ٣-٧ بۆ پارێزگاکانی تر. دواکەوتنی هۆکاری دەرەکی (کەش، ڕێگا، ئاسایش) بەرپرسیاریەتی ئێمە نییە.' },
        { icon: RotateCcw, h: '٨. گەڕاندنەوە و بێزاربوون', p: '٧ ڕۆژ بۆ گەڕاندنەوەی بەرهەمی عەیبدار یان جیاواز. بەرهەمی تایبەت، چاپی 3D، و سۆفتوێری چالاککراو ناگەڕێنرێنەوە.' },
        { icon: ShieldCheck, h: '٩. گەرەنتی و پلانی پاراستن', p: 'گەرەنتی فەرمی لە لاپەڕەی هەر بەرهەمێک. تەنها عەیبی بەرهەمهێنان دەگرێتەوە. پلانی پاراستنی پرینتەر مەرجی جیاوازی هەیە.' },
        { icon: Wrench, h: '١٠. خزمەتی چاککردنەوە', p: 'لە لایەن تەکنیسیەنی پەسەندکراوەوە. تێچوو دوای پشکنین. لیستی پاشەکەوت لە بەرهەمت بکە — ئێمە بەرپرس نین لە لەدەستچوونی داتا.' },
        { icon: Printer, h: '١١. چاپی سێ ڕەهەندی', p: 'پارە لە حسابی نێوبژیدا (Escrow) دەپارێزرێت تا کڕیار وەرگرتن دڵنیا دەکات. کڕیار بەرپرسە لە مافی موڵکی فکری دیزاینەکان.' },
        { icon: Store, h: '١٢. بازاڕی بازرگانان', p: 'بازرگانان بەرپرسن لە بەرهەمەکانیان. LEVONIS کۆمیشنی دیاریکراو وەردەگرێت. بازرگانی بەرهەمی ساختە قەدەغەیە.' },
        { icon: Crown, h: '١٣. کارتی وەفاداری و VIP Plus', p: 'پلەکان: Bronze, Silver, Gold, VIP, VIP Plus. بەکێشە (داشکاندن، گەیاندن) دیاریکراون. کارت پارەی نوێکردنەوەی مانگانەی هەیە.' },
        { icon: Trophy, h: '١٤. پێشبڕکێ، یارینامە و یاری', p: 'پێشبڕکێ، تیمی، صندوقی نهێنی، یاری. بۆ خۆشی و خەڵاتی بازرگانی. بۆت و حسابی فرە قەدەغەیە — خەڵات هەڵدەوەشێتەوە.' },
        { icon: Gift, h: '١٥. خەڵاتەکان و دیاری', p: 'خەڵاتی فیزیکی دوای دڵنیاکردنەوە دەنێردرێن. خەڵاتی دیجیتاڵی خۆکارانە دێت. ماوەی وەرگرتنی خەڵات تا ٣٠ ڕۆژ.' },
        { icon: Ticket, h: '١٦. بەرنامەی هاوبەشی (Referral)', p: 'هەر بەکارهێنەرێک کۆدی هاوبەشی هەیە. خۆ-هاوبەشی و حسابی ساختە قەدەغەیە.' },
        { icon: Users, h: '١٧. ناوەڕۆکی بەکارهێنەر و کۆمەڵگا', p: 'بە ناردنی کۆمێنت/وێنە/فیدیۆ مۆڵەتی جیهانی دەدەی بە LEVONIS بۆ بەکارهێنانیان. ناوەڕۆکی ناشایست قەدەغەیە.' },
        { icon: MessageSquare, h: '١٨. چات و پشتیوانی', p: 'چاتەکان دەکرێت بپارێزرێن بۆ کوالێتی. زمانی ناشایست قەدەغەیە.' },
        { icon: Bell, h: '١٩. ئاگادارکردنەوە و بازرگانی', p: 'بە دروستکردنی هەژمار ڕازیت بە ئاگادارکردنەوەی کارگێڕی. ئاگادارکردنەوەی بازرگانی هەڵبژاردەن.' },
        { icon: Megaphone, h: '٢٠. ڕیڵز و بانەر و ڕیکلام', p: 'ڕیکلامەکان دەکرێت لە لایەن LEVONIS یان هاوبەشانەوە بێن. ئێمە دڵنیاییە لە ڕاستی ڕیکلامی لایەنی سێیەم نادەین.' },
        { icon: Cookie, h: '٢١. کووکی و خەزن', p: 'کووکی بۆ ناسنامە، هەڵبژاردن، و شیکار بەکاردێت. دەتوانیت لە وێبگەڕەکەت بیکوژیتەوە.' },
        { icon: Eye, h: '٢٢. تایبەتمەندی و پاراستنی داتا', p: 'داتاکانت بەپێی پۆلیسی تایبەتمەندی (/privacy) جێبەجێ دەکرێن. ئاسایشی ئینتەرنێت بە تەواوی نابێت گەرەنتی بکرێت.' },
        { icon: Lock, h: '٢٣. ئاسایشی سایبەری', p: 'هاکینگ، DOS، ڕیڤێرس ئینجینیەرینگ، و سکرەپینگی خۆکار قەدەغەن. ڕاپۆرتی هەڕەشە: security@levonisiq.com' },
        { icon: Copyright, h: '٢٤. مافی موڵک و DMCA', p: 'هەموو ناوەڕۆکەکان موڵکی LEVONIS ن. کۆپی یان دووبارە بەکارهێنان بەبێ مۆڵەت قەدەغەیە. DMCA: legal@levonisiq.com' },
        { icon: ImageIcon, h: '٢٥. وێنە و تایبەتمەندیەکانی بەرهەم', p: 'وێنەکان بۆ ڕوونکردنەوەن، ڕەنگ دەکرێت کەمێک جیاواز بێت بەهۆی شاشە.' },
        { icon: Ban, h: '٢٦. بەکارهێنانی قەدەغە', p: 'هەر بەکارهێنانی نایاسایی، فڕتیکار، حسابی ساختە، خراپ بەکارهێنانی خەڵات، یان فرۆشتنی بەرهەمی قەدەغە قەدەغەیە.' },
        { icon: BadgeCheck, h: '٢٧. هەڵسەنگاندن', p: 'هەڵسەنگاندن تەنها بۆ کڕینی پشتڕاستکراوە. هەڵسەنگاندنی ساختە قەدەغەیە.' },
        { icon: FileWarning, h: '٢٨. سنووری بەرپرسیاریەتی', p: 'خزمەتگوزاری "وەک ئێستا" پێشکەش دەکرێت. بەرزترین بەرپرسیاریەتی ئێمە بەهای داواکاریە.' },
        { icon: ShieldCheck, h: '٢٩. قەرەبووکردنەوە', p: 'تۆ ڕازیت LEVONIS قەرەبوو بکەیتەوە لە هەر داواکارییەک کە لە سەرپێچی تۆوە دێت.' },
        { icon: Building2, h: '٣٠. هێزی بەزۆر', p: 'LEVONIS بەرپرس نییە لە دواکەوتن لەبەر هۆکاری دەرەکی (کارەسات، شەڕ، نەخۆشی، بڕیاری حکومەت).' },
        { icon: RefreshCw, h: '٣١. کۆتاییهێنان', p: 'دەتوانیت هەژمارت بداخەیت. ئێمەش دەتوانین هەژماری سەرپێچیکار بداخەین.' },
        { icon: Globe, h: '٣٢. منداڵان', p: 'خزمەتگوزاری بۆ ١٣ ساڵ بەرەو سەرە. منداڵی ١٣-١٨ دەبێت لە ژێر چاودێریی باوک/دایک بێت.' },
        { icon: Scale, h: '٣٣. یاسای فەرمانڕەوا', p: 'یاسای عێراق و دادگاکانی بەغدا.' },
        { icon: ScrollText, h: '٣٤. دابڕانی بەند', p: 'ئەگەر بەندێک نایاسایی بێت، باقی مەرجەکان لەسەر دەمێنن.' },
        { icon: RefreshCw, h: '٣٥. گۆڕانکاری', p: 'دەکرێت مەرجەکان نوێ بکرێنەوە. گۆڕانی گرنگ ١٤ ڕۆژ پێشتر ڕادەگەیەنرێت.' },
        { icon: Mail, h: '٣٦. پەیوەندی', p: 'WhatsApp: +964 783 845 5220 — legal@levonisiq.com — security@levonisiq.com — support@levonisiq.com' },
      ],
    },
  }[language === 'en' ? 'en' : language === 'ku' ? 'ku' : 'ar'];

  const dir = language === 'en' ? 'ltr' : 'rtl';

  return (
    <div className="min-h-screen" dir={dir}>
      <SEO
        title={c.title}
        description={c.desc}
        url="https://levonisiq.com/terms"
        jsonLd={breadcrumbLd([
          { name: 'Home', url: '/' },
          { name: c.title, url: '/terms' },
        ])}
      />
      <main className="container mx-auto px-4 py-10 max-w-3xl">
        <header className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <div className="glass-icon-btn w-11 h-11" aria-hidden="true">
              <Scale className="w-5 h-5 text-primary" />
            </div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-foreground">{c.title}</h1>
          </div>
          <p className="text-muted-foreground mb-2">{c.desc}</p>
          <p className="text-xs text-foreground/60">{c.updated}</p>
        </header>

        <section className="rounded-2xl glass-tile glass-edge-top p-5 md:p-6 mb-6">
          <p className="text-foreground/80 leading-relaxed">{c.intro}</p>
        </section>

        <div className="space-y-4">
          {c.sections.map((s, i) => {
            const Icon = s.icon;
            return (
              <section key={i} className="rounded-2xl glass-tile p-5">
                <div className="flex items-start gap-3 mb-2">
                  <div className="glass-icon-btn w-9 h-9 shrink-0" aria-hidden="true">
                    <Icon className="w-4 h-4 text-primary" />
                  </div>
                  <h2 className="text-lg font-bold text-foreground pt-1.5">{s.h}</h2>
                </div>
                <p className="text-foreground/80 leading-relaxed">{s.p}</p>
              </section>
            );
          })}
        </div>

        <div className="mt-8 flex flex-wrap items-center justify-center gap-3 text-sm">
          <Link to="/privacy" className="text-primary hover:underline">{language === 'en' ? 'Privacy' : language === 'ku' ? 'تایبەتمەندی' : 'سياسة الخصوصية'}</Link>
          <span className="text-muted-foreground">•</span>
          <Link to="/faq" className="text-primary hover:underline">{language === 'en' ? 'FAQ' : language === 'ku' ? 'پرسیار' : 'الأسئلة الشائعة'}</Link>
          <span className="text-muted-foreground">•</span>
          <Link to="/about" className="text-primary hover:underline">{language === 'en' ? 'About' : language === 'ku' ? 'دەربارە' : 'من نحن'}</Link>
        </div>

        <Footer />
      </main>
    </div>
  );
};

export default Terms;
