-- 1) Fix operator precedence bug in detect_price_protection_for_product
CREATE OR REPLACE FUNCTION public.detect_price_protection_for_product(p_product_id uuid, p_new_price numeric)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  inserted_count INTEGER := 0;
  rec RECORD;
  reference_date TIMESTAMPTZ;
BEGIN
  FOR rec IN
    SELECT 
      oi.id AS oi_id,
      oi.order_id,
      oi.product_id,
      oi.product_name_ar,
      oi.unit_price,
      oi.quantity,
      o.user_id,
      o.order_number,
      o.confirmed_at,
      o.delivered_at,
      o.user_confirmed_at,
      o.status,
      p.image_url
    FROM public.order_items oi
    JOIN public.orders o ON o.id = oi.order_id
    LEFT JOIN public.products p ON p.id = oi.product_id
    WHERE oi.product_id = p_product_id
      AND oi.unit_price > p_new_price
      AND o.status IN ('confirmed','processing','shipped','arrived_warehouse','arrived_iraq','on_the_way','purchased','delivered')
      AND (COALESCE(o.user_confirmed_delivery, false) = true OR o.confirmed_at IS NOT NULL)
  LOOP
    reference_date := COALESCE(rec.user_confirmed_at, rec.delivered_at, rec.confirmed_at);
    IF reference_date IS NULL THEN CONTINUE; END IF;
    IF reference_date < (now() - INTERVAL '7 days') THEN CONTINUE; END IF;

    INSERT INTO public.price_protection_claims (
      user_id, order_id, order_item_id, product_id,
      product_name_ar, product_image, order_number,
      purchase_date, old_price, new_price, price_difference,
      quantity, total_refund, status
    ) VALUES (
      rec.user_id, rec.order_id, rec.oi_id, rec.product_id,
      rec.product_name_ar, rec.image_url, rec.order_number,
      reference_date, rec.unit_price, p_new_price, (rec.unit_price - p_new_price),
      rec.quantity, (rec.unit_price - p_new_price) * rec.quantity, 'pending'
    )
    ON CONFLICT (order_item_id) DO NOTHING;

    IF FOUND THEN inserted_count := inserted_count + 1; END IF;
  END LOOP;
  RETURN inserted_count;
END;
$function$;

-- 2) Remove the incorrect pending claims previously generated by the buggy function
DELETE FROM public.price_protection_claims
WHERE status = 'pending'
  AND (price_difference <= 0 OR new_price > old_price)
  AND true;
